### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by BrandonDoesDev** [Maou-Shimazu/Projects-Answers#44]
Problem 1. Folder name varies. Some are uppercase, some lower, some snake case, some Pascal.
Problem 2. Some projects have 10+ programming languages, while others have very few.
Problem 3. File naming. Some project files are named ```main.lang```, while others are names ```projectname.lang``` depending on the project
Problem 4. No one else is contributing Golang solutions :(

These are all annoying problems to fix, big thanks to anyone who decides to fix them <3

**Comment by Omnikar** [comment]
I've fixed this in #41.
